### ISSUE TITLE
getJestConfig() usage example

### ISSUE THREAD

**Issue by lpanger** [yoavniran/gulp-jest-jspm#1]
Do you have code sample on how to use getJestConfig() outside of gulp?

**Comment by yoavniran** [comment]
hi @lpanger 

basically it would be similar to what is shown in the readme here:
https://github.com/yoavniran/gulp-jest-jspm#option-2---continue-using-gulp-jest

so the easy part is getting the config like this:

``` js
const jestConf = gulpJestJspm.getJestConfig(__dirname, {}); //get the jest config

```

The question is, without gulp, how do you run Jest?

if youre just running from command line then you can console out the result of getJestConfig() and save it to a jest.json file. you can then run Jest like this: 
```
$ jest --config ./jest.json
```

but it means that for every change in your system.js config you need to rerun and update your jest.json file with the result from getJestConfig().

or you can run the jest-cli directly and pass it the config object from code:

```` js

const cli = require("jest-cli");

const rootDir =  "your root dir";

const jestOptions = {}; //cli options like debug

const options = {
...jestOptions,
config: getJestConfig(...)
};

cli.runCLI(options, rootDir, (result) =>{
//handle result...
});

```
