### ISSUE TITLE
Extract `getJestConfig` method into standalon module

### ISSUE THREAD

**Issue by ArmorDarks** [yoavniran/gulp-jest-jspm#3]
Hi!

We've talked some time ago in one of Jest repositories about possibility to extract `getJestConfig` into standalone module.

Of course, it would be most useful when https://github.com/facebook/jest/pull/2445 will be merged, but until it happens (probably not soon), we could use another way to pass SystemJS mapping to Jest.

For instance, we have found better way to do this, without need to use Gulp or Grunt (in both case it wasn't that convinient), which you can see here: https://github.com/LotusTM/Kotsu/commit/5a7a7b1e5d54a372f1b97c768cfd266b1782fa8d

But it is quite strange to pull full Gulp task (which also includes `gulp-jest` and `jest-cli`) just to get `getJestConfig`, so it would be great if this method will be moved into standalone module, after all :)

**Comment by ArmorDarks** [comment]
@yoavniran pings you, just in case.

**Comment by yoavniran** [comment]
hi @ArmorDarks , i didnt forget and actually just yesterday started working on this. obviously it takes longer as my real job comes first but im hoping to release the standalone package in the next day or two.
ill let you know once done.

**Comment by ArmorDarks** [comment]
That's great, thanks!

I also think, maybe this method should be renamed to `makeJestConfig` or something like that? Since I was at first confused that method, which named "get" actually loading JSPM file and (sometimes! not all people loading Jest config) loads Jest config, AND producing mappings.

In fact, I'd probably make it pure function and remove loaders at all, since people always can use system Node `fs` to load all 3 pieces (SystemJS config, Jest config, SystemJS files from `jspm_packages`). It will help to avoid awkward situations when you have to support input AND in form of path, and in form of plain Object. Also it will remove burned of thinking how to support default paths in loaders from lib, since, well, it doesn't work well (for example, JSPM already using different default name for config file).

But that's just my random thoughts. We'll be fine with current implementation too.

**Comment by yoavniran** [comment]
hi @ArmorDarks , ive published [jest-jspm](https://www.npmjs.com/package/jest-jspm)
and updated this package to depend on it.  let me know if you get to use it and if you find issues.
thanks

**Comment by ArmorDarks** [comment]
Nice, thanks! As a side benefit, Gulp task is now much more readable :)

Going to test it soon. I'll let you know in `jest-jspm` repository if something goes wrong.
